import React from 'react'

const BackgroundElements = ({ }) => {
    return (
        <div className="container">
  <div className="season"></div>
  <div className="sun"></div>
  <div className="rainbow">
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
    <div className="rainbow-colour"></div>
  </div>
  <div className="cloud-group">
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
    <div className="cloud">
      <div className="weather-container">
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="snow"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
        <div className="rain"></div>
      </div>
    </div>
  </div>
  <div className="base">
    <div className="bush-group">
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
      <div className="bush"></div>
    </div>
    <div className="rabbit animated">
      <div className="head">
        <div className="ear"></div>
        <div className="ear"></div>
      </div>
    </div>
    <div className="tree-group">
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
        <div className="branch"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
        <div className="branch-two">
          <div className="tree-top"></div>
        </div>
        <div className="branch-two">
          <div className="tree-top"></div>
        </div>
        <div className="branch-two">
          <div className="tree-top"></div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top">
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
        </div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
        <div className="flower">
          <div className="flower-in"></div>
          <div className="petal"></div>
          <div className="petal"></div>
          <div className="petal"></div>
        </div>
        <div className="flower">
          <div className="flower-in"></div>
          <div className="petal"></div>
          <div className="petal"></div>
          <div className="petal"></div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"> </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
        <div className="branch">
          <div className="branch-in"></div>
          <div className="pine-cone-row">
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
            <div className="pine-cone"></div>
          </div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
      </div>
      <div className="tree">
        <div className="trunk"> </div>
        <div className="tree-top">
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
        </div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
        <div className="flower">
          <div className="flower-in"></div>
          <div className="petal"></div>
          <div className="petal"></div>
          <div className="petal"></div>
        </div>
        <div className="flower">
          <div className="flower-in"></div>
          <div className="petal"></div>
          <div className="petal"></div>
          <div className="petal"></div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top"> </div>
        <div className="tree-top"></div>
        <div className="tree-top"></div>
        <div className="branch-two">
          <div className="tree-top"></div>
        </div>
        <div className="branch-two">
          <div className="tree-top"></div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top">
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
        </div>
        <div className="tree-top">
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
        </div>
        <div className="tree-top">
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
          <div className="cone"> </div>
        </div>
      </div>
      <div className="tree">
        <div className="trunk"></div>
        <div className="tree-top">
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
          <div className="cone">      </div>
        </div>
        <div className="tree-top">
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
          <div className="cone">       </div>
        </div>
        <div className="tree-top">
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
          <div className="cone"></div>
        </div>
      </div>
    </div>
  </div>
</div>
    )
}

export default React.memo(BackgroundElements)